// <auto-generated />
using System;
using Assignment10.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment10.Migrations
{
    [DbContext(typeof(Assignment_10_Context))]
    [Migration("20211001112140_NewDbDay10")]
    partial class NewDbDay10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment10.Models.Department_Model", b =>
                {
                    b.Property<int>("Department_ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Employees")
                        .HasColumnType("int");

                    b.HasKey("Department_ModelId");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("Assignment10.Models.Employees_Model", b =>
                {
                    b.Property<int>("Employees_ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Department_ModelId")
                        .HasColumnType("int");

                    b.Property<int>("Emp_Dep_Id")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employees_ModelId");

                    b.HasIndex("Department_ModelId");

                    b.ToTable("Emps");
                });

            modelBuilder.Entity("Assignment10.Models.Employees_Model", b =>
                {
                    b.HasOne("Assignment10.Models.Department_Model", "Department_Model")
                        .WithMany("employees_list")
                        .HasForeignKey("Department_ModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
